# fly.toml app configuration file generated for gsm-backend

app = "gsm-backend"
primary_region = "bom"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[processes]
  app = "gunicorn core.wsgi"
  simulator = "python manage.py simulate_market_loop"

[deploy]
  release_command = "python manage.py migrate"

[[cron]]
  schedule = "*/10 * * * *"
  command = "python manage.py unlock_trading"

[[cron]]
  schedule = "*/10 * * * *"
  command = "python manage.py end_tournament"

