app = "gsm-backend"
primary_region = "bom"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[processes]
app = "gunicorn core.wsgi"
simulator = "python manage.py simulate_market_loop"
cron = "sleep infinity"

[deploy]
  release_command = "python manage.py migrate"

[[cron]]
  schedule = "*/10 * * * *"
  command = "python manage.py unlock_trading"
  processes = ["cron"]

[[cron]]
  schedule = "*/10 * * * *"
  command = "python manage.py end_tournament"
  processes = ["cron"]