# fly.toml app configuration file generated for gsm-backend on 2025-07-06T13:21:34-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gsm-backend'
primary_region = 'bom'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1


[processes]
app = "gunicorn core.wsgi"  # This is your main web app
simulator = "python manage.py simulate_market_loop"  # Background simulation
