# Generated by Django 5.2 on 2025-07-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_monthlytournamententry'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlytournamententry',
            name='final_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='monthlytournamententry',
            name='tournament_key',
            field=models.CharField(default='default_key', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_trading_locked',
            field=models.BooleanField(default=True),
        ),
    ]
