# Generated by Django 5.2 on 2025-07-12 08:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_monthlytournamententry_final_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_trading_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='monthlytournamententry',
            unique_together={('user', 'tournament_key')},
        ),
    ]
