# Generated by Django 5.2 on 2025-07-16 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_tournament_portfolio_tournamententry_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='tournament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.tournament'),
            preserve_default=False,
        ),
    ]
